### ISSUE TITLE
Development Dead??

### ISSUE THREAD

**Issue by ajmalmsali** [blackberry/jQueryMobile-BB10-Theme#143]
Development dead on this project?

**Comment by thtro** [comment]
Please answer on this question.
cc @astanley @kwallis

**Comment by astanley** [comment]
No, not officially. However resources have been redirected elsewhere.

**Comment by thtro** [comment]
So...this theme is halted. bbUI.js development is awfully slow and will be rebuilt from the ground up anyway, what UI framework should we use to ensure future compatibility? I believe that HTML5 development has been really neglected from BB's side, in respect to available frameworks. This should change fast because it hurts everybody!
